feat: Payment 초기 세팅
baedal-legend/foody pull request #26
Opened 2024-08-25 14:34 UTC by linavell

# 개요
Payment 도메인 초기 세팅을 구현합니다.

# 작업 내용
- Payment 도메인 설계
- 필요한 Controller, Repo, Service 구현

close #25

2024-08-25 14:49 UTC, choi-ys requested changes
고생하셨어요 👍 

같이 논의해보면 좋을 만한 사항을 코멘트에 남겨보았습니다!

2024-08-25 14:49 UTC, choi-ys commented on src/main/java/com/sparta/baedallegend/payment/domain/Payment.java
> +    private Long payAmount;
테이블 명세서에 주문 금액이 Long으로 표기되어 있네요..
![image](https://github.com/user-attachments/assets/9cf1e80b-d275-4266-a73c-20aec1e8e04e)

DECIMAL을 고려해보는건 어떻게 생각하세요?
큰 금액을 다룰 수 있을 만큼 바이트 수도 크고, 소수점을 다루거나 연산에 편리한 메서드가 제공되어서 이점이 있을 것 같아요!

2024-08-25 16:48 UTC, uzjaee reviewed
작성하시느라 고생하셨습니다!
NoArgsConstructor에 대해 참고할만 사항을 리뷰로 남겨두었습니다!

2024-08-25 16:48 UTC, uzjaee commented on src/main/java/com/sparta/baedallegend/payment/domain/Payment.java
> +@NoArgsConstructor
@NoArgsConstructor(access = AccessLevel.PROTECTED)로 하는건 어떠신가요?
default로 설정된 public 제어자도 좋지만
protected로 표기해놓는 것이 의도를 알기좋고 다른 도메인과 통일성을 주기때문에 좋을거 같습니다!

2024-08-26 01:04 UTC, linavell commented on src/main/java/com/sparta/baedallegend/payment/domain/Payment.java
> +@NoArgsConstructor
앗 맞네요 까먹었습니다!

2024-08-27 12:05 UTC, linavell commented on src/main/java/com/sparta/baedallegend/payment/domain/Payment.java
> +    private Long payAmount;
좋은 것 같슴니다~!

2024-08-27 12:09 UTC, linavell commented
말씀해주신 부분들 수정하였습니다 !

2024-08-27 12:26 UTC, choi-ys approved these changes
고생 많으셨습니다.
저는 해당 PR 종료해도 될 것 같아요!
용재님 확인하시고 추가 수정 사항 없으시면 종료해주세요~!

2024-08-27 13:21 UTC, merged